[graph]
all-features = true

[advisories]
ignore = [
    { id = "RUSTSEC-2024-0370", reason = "No safe upgrade is available `proc-macro-error`." },
]

[bans]
allow-wildcard-paths = true
multiple-versions = "allow"
wildcards = "deny"

[licenses]
allow = ["Apache-2.0", "BSL-1.0", "MIT", "Unicode-3.0", "Zlib"]
confidence-threshold = 1.0

[sources]
unknown-git = "deny"
unknown-registry = "deny"

[sources.allow-org]
github = ["RustForWeb"]
